//! # MQTT Constants
//! 
//! This module defines all MQTT protocol constants including property identifiers
//! and payload format indicators for MQTT 5.0.

// MQTT v5 Property Identifiers
pub const PROPERTY_PAYLOAD_FORMAT_INDICATOR: u8 = 0x01;
pub const PROPERTY_MESSAGE_EXPIRY_INTERVAL: u8 = 0x02;
pub const PROPERTY_CONTENT_TYPE: u8 = 0x03;
pub const PROPERTY_RESPONSE_TOPIC: u8 = 0x08;
pub const PROPERTY_CORRELATION_DATA: u8 = 0x09;
pub const PROPERTY_SUBSCRIPTION_IDENTIFIER: u8 = 0x0B;
pub const PROPERTY_SESSION_EXPIRY_INTERVAL: u8 = 0x11;
pub const PROPERTY_ASSIGNED_CLIENT_IDENTIFIER: u8 = 0x12;
pub const PROPERTY_SERVER_KEEP_ALIVE: u8 = 0x13;
pub const PROPERTY_AUTHENTICATION_METHOD: u8 = 0x15;
pub const PROPERTY_AUTHENTICATION_DATA: u8 = 0x16;
pub const PROPERTY_REQUEST_PROBLEM_INFORMATION: u8 = 0x17;
pub const PROPERTY_WILL_DELAY_INTERVAL: u8 = 0x18;
pub const PROPERTY_REQUEST_RESPONSE_INFORMATION: u8 = 0x19;
pub const PROPERTY_RESPONSE_INFORMATION: u8 = 0x1A;
pub const PROPERTY_SERVER_REFERENCE: u8 = 0x1C;
pub const PROPERTY_REASON_STRING: u8 = 0x1F;
pub const PROPERTY_RECEIVE_MAXIMUM: u8 = 0x21;
pub const PROPERTY_TOPIC_ALIAS_MAXIMUM: u8 = 0x22;
pub const PROPERTY_TOPIC_ALIAS: u8 = 0x23;
pub const PROPERTY_MAXIMUM_QOS: u8 = 0x24;
pub const PROPERTY_RETAIN_AVAILABLE: u8 = 0x25;
pub const PROPERTY_USER_PROPERTY: u8 = 0x26;
pub const PROPERTY_MAXIMUM_PACKET_SIZE: u8 = 0x27;
pub const PROPERTY_WILDCARD_SUBSCRIPTION_AVAILABLE: u8 = 0x28;
pub const PROPERTY_SUBSCRIPTION_IDENTIFIERS_AVAILABLE: u8 = 0x29;
pub const PROPERTY_SHARED_SUBSCRIPTION_AVAILABLE: u8 = 0x2A;

// MQTT v5 Payload Format Indicator values
pub const PAYLOAD_FORMAT_INDICATOR_UNSPECIFIED: u8 = 0x00;
pub const PAYLOAD_FORMAT_INDICATOR_UTF8: u8 = 0x01;
